version: "4.27"
services:
  bot:
    build: .
    command: sh -c "python -m bot"

    volumes:
      - .:/app:rw
      - my_volume:/otp

    env_file:
      - .env
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  my_volume:
    driver: local